//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FastRW
{
    using System;
    using System.Collections.Generic;
    
    public partial class arhiv
    {
        public long id_prod1 { get; set; }
        public Nullable<long> id_prod2 { get; set; }
        public long id_isp { get; set; }
        public short nm_step { get; set; }
        public System.DateTime dat { get; set; }
        public Nullable<float> p1 { get; set; }
        public Nullable<float> p2 { get; set; }
        public Nullable<float> p3 { get; set; }
        public Nullable<float> p4 { get; set; }
        public Nullable<float> p5 { get; set; }
        public Nullable<float> p6 { get; set; }
        public Nullable<float> p7 { get; set; }
        public Nullable<float> p8 { get; set; }
        public Nullable<float> p9 { get; set; }
        public Nullable<float> p10 { get; set; }
        public Nullable<float> p11 { get; set; }
        public Nullable<float> p12 { get; set; }
        public Nullable<float> p13 { get; set; }
        public Nullable<float> p14 { get; set; }
        public Nullable<float> p15 { get; set; }
        public Nullable<float> p16 { get; set; }
        public Nullable<float> p17 { get; set; }
        public Nullable<float> p18 { get; set; }
        public Nullable<float> p19 { get; set; }
        public long id { get; set; }
        public Nullable<short> per { get; set; }
        public string faza { get; set; }
        public long i { get; set; }
    }
}
