//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FastRW
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tab
    {
        public Nullable<int> param1 { get; set; }
        public Nullable<int> param2 { get; set; }
        public Nullable<double> param3 { get; set; }
        public Nullable<double> param4 { get; set; }
        public int param5 { get; set; }
    }
}
